In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('StudentPerformanceFactors_Cleaned.csv')
df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6372,25,69,High,Medium,No,7,76,Medium,Yes,1,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6373,23,76,High,Medium,No,8,81,Medium,Yes,3,Low,High,Public,Positive,2,No,High School,Near,Female,69
6374,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6375,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6376,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [3]:
from sklearn.preprocessing import LabelEncoder
categorical_columns = df.select_dtypes(include=["object"]).columns

In [4]:
label_encoder = {}
for col in categorical_columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoder[col] = le

In [5]:
df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,1,0,0,7,73,1,1,0,1,2,1,2,3,0,1,2,1,67
1,19,64,1,2,0,8,59,1,1,2,2,2,1,0,4,0,0,1,0,61
2,24,98,2,2,1,7,91,2,1,2,2,2,1,1,4,0,2,2,1,74
3,29,89,1,2,1,8,98,2,1,1,2,2,1,0,4,0,1,1,1,71
4,19,92,2,2,1,6,65,2,1,3,2,0,1,1,4,0,0,2,0,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6372,25,69,0,2,0,7,76,2,1,1,0,2,1,2,2,0,1,2,0,68
6373,23,76,0,2,0,8,81,2,1,3,1,0,1,2,2,0,1,2,0,69
6374,20,90,2,1,1,6,65,1,1,3,1,2,1,0,2,0,2,2,0,68
6375,10,86,0,0,1,6,91,0,1,2,1,2,0,2,3,0,1,0,0,68
6376,15,67,2,1,1,9,94,2,1,0,2,2,1,2,4,0,2,2,1,64

In [6]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [8]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [10]:
import numpy as np
sample_input = [
    23,  # Hours_Studied
    84,  # Attendance
    1,   # Parental_Involvement (encoded value)
    0,   # Access_to_Resources (encoded value)
    0,   # Extracurricular_Activities (encoded value)
    7,   # Sleep_Hours
    73,  # Previous_Scores
    1,   # Motivation_Level (encoded value)
    1,   # Internet_Access (encoded value)
    0,   # Tutoring_Sessions
    1,   # Family_Income (encoded value)
    2,   # Teacher_Quality (encoded value)
    1,   # School_Type (encoded value)
    2,   # Peer_Influence (encoded value)
    3,   # Physical_Activity
    0,   # Learning_Disabilities (encoded value)
    1,   # Parental_Education_Level (encoded value)
    2,   # Distance_from_Home (encoded value)
    1,   # Gender (encoded value)
]

# Reshape input to fit modelâ€™s expected format (1 sample, number of features)
sample_input = np.array(sample_input).reshape(1, -1)
sample_prediction = regressor.predict(sample_input)
print("Predicted outcome for the sample input:", sample_prediction[0])

Predicted outcome for the sample input: 69.15143576548226

In [11]:
from sklearn.metrics import mean_absolute_error
y_pred = regressor.predict(X_test)
mean_absolute_error(y_test,y_pred)

1.028672176320524

In [15]:
from sklearn.metrics import mean_squared_error
y_pred = regressor.predict(X_test)
mean_squared_error(y_test,y_pred)

4.91157729633586

In [13]:
from sklearn.metrics import r2_score
y_pred = regressor.predict(X_test)
r2_score(y_test,y_pred)

0.6678628659367791